/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Arkify (https://sketchfab.com/arkify)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/black-leather-heeled-shoe-5878948e8e17404791b7403019320f8c
title: Black Leather Heeled Shoe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shoe.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[1.31, -0.06, 0.2]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
            <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
            <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
            <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
            <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
            <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
            <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
            <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
            <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
            <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
            <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
            <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
            <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoe.gltf')
