/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: emelyarules (https://sketchfab.com/emelyarules)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/womens-bag-f5bef92473d94fc5b2b01c16a02154aa
title: Women's bag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/womens_bag.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.map_BagWomen_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/womens_bag.gltf')
